# Generated by Django 2.2.13 on 2020-10-12 09:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0019_comment_like_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentsLike',
            new_name='CommentLike',
        ),
    ]
