# Generated by Django 2.2.13 on 2020-10-12 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_auto_20201012_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='like_count',
            new_name='comm_like_count',
        ),
    ]
